export const COURSES_DATA = [
  {
    name: "Hyaluron Pen Lip Volume Kit included",
    slug: "hyaluron-pen-lip-volume-kit-included",
    trainerName: "Carmen Scortanu",
    price: 1000,
    duration: "12h",
    description: "Professional Hyaluron Pen training for lip volume enhancement with complete kit included",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/pQeodcyBxbOOzOqE.jpg",
  },
  {
    name: "Corrective Morphology",
    slug: "corrective-morphology",
    trainerName: "Carmen Scortanu",
    price: 1000,
    duration: "12h",
    description: "Advanced corrective morphology techniques for facial aesthetics",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/qfGApyyMjQDCjWxC.jpg",
  },
  {
    name: "Dermopigmentation",
    slug: "dermopigmentation-course",
    trainerName: "Carmen Scortanu",
    price: 1000,
    duration: "12h",
    description: "Comprehensive dermopigmentation training for permanent makeup applications",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/GBiIrEhekTiGnMey.jpg",
  },
  {
    name: "Microblading Course Eyebrows Without KIT",
    slug: "microblading-course-eyebrows-without-kit",
    trainerName: "Carmen Scortanu",
    price: 790,
    duration: "8h",
    description: "Professional microblading course for eyebrows without kit",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/ERGGdbgnhffvIbjH.jpg",
  },
  {
    name: "Hyaluron Pen Lip Volume Without Kit",
    slug: "hyaluron-pen-lip-volume-without-kit",
    trainerName: "Carmen Scortanu",
    price: 500,
    duration: "8h",
    description: "Hyaluron Pen training for lip volume enhancement without kit",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/pQeodcyBxbOOzOqE.jpg",
  },
  {
    name: "Hyaluron pen course for other areas. including KIT",
    slug: "hyaluron-pen-other-areas-with-kit",
    trainerName: "Carmen Scortanu",
    price: 1000,
    duration: "8h",
    description: "Hyaluron Pen training for various facial areas with complete kit included",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/yKbYUJpSluPZVnzZ.jpg",
  },
  {
    name: "Hyaluron pen course for other areas. Without KIT",
    slug: "hyaluron-pen-other-areas-without-kit",
    trainerName: "Carmen Scortanu",
    price: 500,
    duration: "8h",
    description: "Hyaluron Pen training for various facial areas without kit",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/yKbYUJpSluPZVnzZ.jpg",
  },
  {
    name: "Microblading course for men's eyebrows, realistic technique, without KIT",
    slug: "microblading-mens-eyebrows-without-kit",
    trainerName: "Carmen Scortanu",
    price: 1200,
    duration: "72h",
    description: "Specialized microblading course for men's eyebrows using realistic technique without kit",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/SLkTRhLxFMqnVoJd.jpg",
  },
  {
    name: "Microblading course for men's eyebrows, realistic technique, including KIT",
    slug: "microblading-mens-eyebrows-with-kit",
    trainerName: "Carmen Scortanu",
    price: 1800,
    duration: "8h",
    description: "Specialized microblading course for men's eyebrows using realistic technique with kit included",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/SLkTRhLxFMqnVoJd.jpg",
  },
  {
    name: "Microblading Advanced Course for Womens",
    slug: "microblading-advanced-womens",
    trainerName: "Carmen Scortanu",
    price: 800,
    duration: "8h",
    description: "Advanced microblading techniques for women's eyebrows",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/ERGGdbgnhffvIbjH.jpg",
  },
];

export const SERVICES_DATA = [
  {
    name: "Microblading",
    slug: "microblading",
    price: 450,
    category: "eyebrows",
    duration: 120,
    description: "Professional eyebrow microblading treatment",
    longDescription: "Microblading is a manual method of permanent cosmetics for your eyebrows which creates extremely fine natural looking hair strokes. Ideal for someone who has experienced hair loss and wants to achieve very natural thick, full looking eyebrows. The effects last 18-24 months.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/ERGGdbgnhffvIbjH.jpg",
  },
  {
    name: "Acne Treatment",
    slug: "acne-treatment",
    price: 350,
    category: "skin",
    duration: 60,
    description: "Comprehensive acne treatment solution",
    longDescription: "Advanced acne treatment combining multiple technologies to target the root causes of acne, reduce breakouts, and improve overall skin health.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/CVUpqfAqgXGAFvEw.jpg",
  },
  {
    name: "Carbon Peel Laser",
    slug: "carbon-peel-laser",
    price: 180,
    category: "facial",
    duration: 45,
    description: "Advanced carbon peel laser facial",
    longDescription: "Deep cleansing facial treatment using carbon lotion and laser technology to remove impurities, reduce pore size, and rejuvenate the skin.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/kIPIIRmwSXlcmodo.jpg",
  },
  {
    name: "Dermopigmentation",
    slug: "dermopigmentation",
    price: 600,
    category: "facial",
    duration: 120,
    description: "Semi-permanent cosmetic pigmentation",
    longDescription: "Advanced semi-permanent cosmetic procedure to enhance and define facial features through specialized pigment implantation.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/GBiIrEhekTiGnMey.jpg",
  },
  {
    name: "Facial Rejuvenation",
    slug: "facial-rejuvenation",
    price: 2800,
    category: "facial",
    duration: 180,
    description: "Complete facial rejuvenation treatment",
    longDescription: "Multi-faceted approach combining laser therapy, chemical peels, microneedling, and radiofrequency to restore youthful vitality.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/CRnYLycCDKDnXXly.jpg",
  },
  {
    name: "Jawline Contouring",
    slug: "jawline-contouring",
    price: 650,
    category: "facial",
    duration: 90,
    description: "Jawline definition and contouring",
    longDescription: "Non-invasive treatment to enhance jawline definition and structure using dermal fillers and skin-tightening techniques.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/qLlcTAnkSAKUjzxS.jpg",
  },
  {
    name: "Lip Micropigmentation",
    slug: "lip-micropigmentation",
    price: 650,
    category: "lips",
    duration: 90,
    description: "Semi-permanent lip color enhancement",
    longDescription: "Semi-permanent cosmetic treatment to enhance natural lip shape and color by depositing pigment into the upper layers of the lips.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/QoAhPlcvYrugCrVu.jpg",
  },
  {
    name: "Lip Shape Correction",
    slug: "lip-shape-correction",
    price: 450,
    category: "lips",
    duration: 60,
    description: "Lip shape and contour correction",
    longDescription: "Specialized treatment to enhance and refine natural lip contours, promoting a fuller, more balanced appearance.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/JzwrySEwHZcQXQUs.jpg",
  },
  {
    name: "Melasma Treatment",
    slug: "melasma-treatment",
    price: 550,
    category: "skin",
    duration: 60,
    description: "Specialized melasma hyperpigmentation treatment",
    longDescription: "Advanced treatment combining chemical peels, laser therapy, and topical agents to reduce melanin production and lighten dark spots.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/DXSecXnwwvjbkrWG.jpg",
  },
  {
    name: "Lip Volumization",
    slug: "lip-volumization",
    price: 400,
    category: "lips",
    duration: 45,
    description: "Lip volume enhancement with dermal fillers",
    longDescription: "Quick, non-surgical treatment using advanced dermal fillers to enhance lip fullness and improve contour with minimal downtime.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/yKbYUJpSluPZVnzZ.jpg",
  },
  {
    name: "Nasolabial Folds",
    slug: "nasolabial-folds",
    price: 250,
    category: "facial",
    duration: 45,
    description: "Nasolabial fold reduction treatment",
    longDescription: "Non-invasive treatment to reduce the appearance of nasolabial folds and improve facial contours.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/KmanTFsSRkesmoVR.jpg",
  },
  {
    name: "Nose Shape Correction",
    slug: "nose-shape-correction",
    price: 550,
    category: "facial",
    duration: 60,
    description: "Non-surgical nose shape correction",
    longDescription: "Non-surgical nose enhancement using dermal fillers and advanced techniques to achieve desired shape and balance.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/ioVJdcXcoihCEcUb.jpg",
  },
  {
    name: "Permanent Make-up",
    slug: "permanent-makeup",
    price: 800,
    category: "facial",
    duration: 120,
    description: "Professional permanent makeup application",
    longDescription: "Professional permanent makeup application for eyebrows, eyeliner, and lips using advanced pigmentation techniques.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/LZlsIcTsDURRSOGd.jpg",
  },
  {
    name: "Plasma Lift",
    slug: "plasma-lift",
    price: 600,
    category: "facial",
    duration: 90,
    description: "Non-surgical plasma lift facelift",
    longDescription: "Advanced non-surgical facelift treatment using plasma technology to tighten skin and reduce signs of aging.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/SxOLEHuomgYVhrgD.jpg",
  },
  {
    name: "Radiofrequency Microneedling",
    slug: "radiofrequency-microneedling",
    price: 180,
    category: "skin",
    duration: 60,
    description: "Advanced RF microneedling treatment",
    longDescription: "Cutting-edge treatment combining radiofrequency and microneedling to stimulate collagen production and rejuvenate skin.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/JmTSWpzzWuPigQni.jpg",
  },
  {
    name: "Rhinofiller",
    slug: "rhinofiller",
    price: 200,
    category: "facial",
    duration: 45,
    description: "Non-surgical nose enhancement with fillers",
    longDescription: "Non-surgical nose enhancement using dermal fillers to achieve desired shape without surgery.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/JMarJYoqEuBPQVHc.jpg",
  },
  {
    name: "Russian Lips",
    slug: "russian-lips",
    price: 700,
    category: "lips",
    duration: 90,
    description: "Russian technique lip enhancement",
    longDescription: "Advanced lip enhancement using the Russian technique to create fuller, more defined lips with natural-looking results.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/aZqMaLlkmbazUpxl.jpg",
  },
  {
    name: "Skin Booster",
    slug: "skin-booster",
    price: 300,
    category: "skin",
    duration: 45,
    description: "Advanced skin hydration and rejuvenation",
    longDescription: "Innovative treatment to boost skin hydration and rejuvenation using advanced techniques and premium products.",
    imageUrl: "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/tUXENpHrBZknnLFp.jpg",
  },
];

export const LOGO_URL = "https://files.manuscdn.com/user_upload_by_module/session_file/310519663345623151/WMmkIdeGQmlJlSlr.png";
